name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11 ]

    name: Java ${{ matrix.java-version }} build
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
        cache: 'gradle'
    - name: Run Compile Tests
      run: ./gradlew assembleRelease
    - name: Run Unit Tests
      run: ./gradlew :app:testProdReleaseUnitTest :wear:testProdReleaseUnitTest
    - name: Check Output
      run: bash ./etc/CheckBuild/check-release.sh test
